### ISSUE TITLE
Bus stop module suddenly stopped declaring departures

### ISSUE THREAD

**Issue by airborneinferno** [nwootton/MMM-UKLiveBusStopInfo#13]
Having successfully got the bus stop and train modules working a week or so ago, I've noticed that the Bus modules now shows that there are "No departures scheduled". I've queried the TransportAPI and think it is giving the required info.
I had a notification that the module was two commits behind and so I ran a git pull and installed, but to no avail.

I haven't really tinkered with the settings within the module and so it is running all the standard settings...

{
module: 'MMM-UKLiveBusStopInfo',
position: 'bottom_left',
header: 'Departures'
config: {
atcocode: '490005445C',
app_id: '.....',
app_key: '.....',
limit: 5,
nextBuses: 'no'
showRealTime: false,
showDelay: false,
}

As I say, my AppId and AppKey are working fine on the train module, so I know that's not a factor.
I am a complete RaspPi, Linux and MM noob, so apologies if I've made a simple goof. I am also aware that you are no longer working on this module, but if anyone else has any ideas, it'd be much appreciated. My son likes to see when his next buses are due!

**Comment by amabirts** [comment]
Experiencing the exact same issue here, had made some changes and thought I might have created an error somewhere - but I can’t find anything that I’ve done. So may be something deeper. There are definitely buses out there!

**Comment by AndyHazz** [comment]
I've done a bit of tinkering with this in the past, enough for me to think I've found the problem but not enough to know how to fix it ...

It looks like the 'group=no' query parameter is being ignored by transportapi.com, and is giving a response as if you asked for 'group=route' and grouping the busses by each bus number, instead of all under one grouping called 'all' which this module is expecting.

The documentation and API demo here has the same problem - it says what the group parameter should do, but setting it has no effect on the output: https://developer.transportapi.com/docs?raml=https://transportapi.com/v3/raml/transportapi.raml##uk_bus_stop_atcocode_live_json

So ... there's nothing wrong with the magicmirror module but something is up with the transport api, at least that's how it looks to me. Maybe their change is intentional and they'll update their documentation to match, or maybe it's just a temporary bug at their end and it'll be fixed soon.

In the meantime if anyone could figure out how to update the module to parse a JSON response grouped by bus number, that'd be great!

**Comment by AndyHazz** [comment]
I sent an issue report to transportapi.com this morning, haven't had a reply yet but looks like they fixed it 👍

**Comment by airborneinferno** [comment]
Wow, well done Andy! You're right, they've fixed it within the last two hours. Eldest son will be delighted to be able to check bus times before leaving in the morning! All sorted.
