### ISSUE TITLE
Atcocode

### ISSUE THREAD

**Issue by jste84** [nwootton/MMM-UKLiveBusStopInfo#14]
Hi,

This is possibly me being a complete newbie at this. I can see the module works (I've tried using another atcocode)

I'm trying to use the Atco code for my stop, which I believe is 73723972 but this doesn't load.

I'm posting here in the hope someone can help and tell me what I'm doing wrong.

If this isn't the best place to post... Then please accept my apologies.

**Comment by imp3ga** [comment]
I know this was a few months ago but thought I would share how I managed to work out my bus stop because I also found it confusing!

If you are like me, you were trying to find somewhere online where you could get the Atco code, and ended up finding something that maybe might be the right number but not entirely sure. I imagine you are stuck on loading becuase you've actually used the wrong number, which is easy to do (I definitely did)

I ended up finding the right code by downloading the NaPTAN dataset in CSV format from here: https://data.gov.uk/dataset/ff93ffc1-6656-47d8-9155-85ea0b8f2251/national-public-transport-access-nodes-naptan 
(click on the link Zipped CSV Format)

Then I had a look in the 'Stops.csv' file. I am not entirely sure what the formatting of this file is exactly, but given the example we have of 490015165B (which was provided as an example by the developer), it seems like the first column number is the Atco code, and the 5th column is the stop name (the column which follows "", ""). 

So then I searched this file for the bus stop I'm interrested in but prefixed with "", "" (so, I searched "","",BusStopName), there were 6 or 7 with the same or similar names (I guess there must be other cities with this same bus stop name), so I copied all of the first numbers on those lines and saved them somwhere else. Then I just had to keep trying each one of these 6 or 7 until the module displayed the right bus times!

**Comment by mahirmm** [comment]
> I know this was a few months ago but thought I would share how I managed to work out my bus stop because I also found it confusing!
> 
> If you are like me, you were trying to find somewhere online where you could get the Atco code, and ended up finding something that maybe might be the right number but not entirely sure. I imagine you are stuck on loading becuase you've actually used the wrong number, which is easy to do (I definitely did)
> 
> I ended up finding the right code by downloading the NaPTAN dataset in CSV format from here: https://data.gov.uk/dataset/ff93ffc1-6656-47d8-9155-85ea0b8f2251/national-public-transport-access-nodes-naptan
> (click on the link Zipped CSV Format)
> 
> Then I had a look in the 'Stops.csv' file. I am not entirely sure what the formatting of this file is exactly, but given the example we have of 490015165B (which was provided as an example by the developer), it seems like the first column number is the Atco code, and the 5th column is the stop name (the column which follows "", "").
> 
> So then I searched this file for the bus stop I'm interrested in but prefixed with "", "" (so, I searched "","",BusStopName), there were 6 or 7 with the same or similar names (I guess there must be other cities with this same bus stop name), so I copied all of the first numbers on those lines and saved them somwhere else. Then I just had to keep trying each one of these 6 or 7 until the module displayed the right bus times!

Thank you so much - this worked perfectly. An additional note: If you click on your specific bus stop on Google Maps, it **sometimes** displays a mix of letters on the left panel which references the stop eg. "lanpawgp". You can then use this code to search for your bus stop in the csv file within the 2nd column.

**Comment by nwootton** [comment]
Go to OpenstreetMap.org
On the right hand side of the screen, select the layers option and then the "Transport Map"

![Screenshot 2022-05-04 at 09 10 17](https://user-images.githubusercontent.com/7591978/166644210-3f23b68a-9292-44e9-8f0e-522976654642.png)

Find the bus stop that you want the info for and with the "Query features" enabled on the right menu, click on it
![Screenshot 2022-05-04 at 09 12 04](https://user-images.githubusercontent.com/7591978/166644436-08968bea-1fc4-4d1e-80dd-f56f888fa5c3.png)

On the left hand side you should get the query results that show the bus stop and other associated Transport info
![Screenshot 2022-05-04 at 09 13 08](https://user-images.githubusercontent.com/7591978/166644547-8059e102-73bf-495d-b537-9500f53e2cba.png)

Clicking on the bus stop link will open a sub-query that lists the information about the selected bus stop. The ATCO code is listed here as the naptan:AtcoCode
![Screenshot 2022-05-04 at 09 13 56](https://user-images.githubusercontent.com/7591978/166644752-102e434e-c658-4ccd-a1a6-523c79037643.png)

So in this case the code to use would be _40004406156A_

**Comment by nwootton** [comment]
Added this info to the documentation
